# Basic Python

## 1. Split this string

In [45]:
s = "Hi there Sam!"

In [46]:
x = s.split();
print(x)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [47]:
planet = "Earth"
diameter = 12742

In [48]:
text = "The diameter of {} is {} kilometers"
print(text.format(planet,diameter))

The diameter of Earth is 12742 kilometers

## 3. In this nest dictionary grab the word "hello"

In [49]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [50]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello

# Numpy

In [51]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [52]:
zeros=np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [53]:
fives=np.ones(10)*5
print(fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 20 to 35

In [54]:
array=np.arange(20,36,2)
print(array)

[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [55]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [56]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [57]:
import pandas as pd

In [58]:
technologies = {
    'Courses':["Spark","PySpark","Python"],
    'Fee' :[20000,25000,22000]
}
df = pd.DataFrame(technologies)
print(df)

   Courses    Fee
0    Spark  20000
1  PySpark  25000
2   Python  22000

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [59]:
per1 = pd.date_range(start ='1-1-2023', 
         end ='2-10-2023')
  
for val in per1:
    print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [60]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [61]:
df = pd.DataFrame(lists, columns =['1-digit', 'letters' ,'2-digit']) 
print(df)

   1-digit letters  2-digit
0        1     aaa       22
1        2     bbb       25
2        3     ccc       24